#!/bin/sh
# ===========================================================================
# A script to enable laptop power saving features for #! & Debian GNU+linux.
# Generally speaking, this script should automatically switch powertop's 
# "Tunables" which proved to make significant impact in power consumption 
# while running on battery.
#
# Script originally created by hardran3 at:
# http://crunchbanglinux.org/forums/topic/11954
# 
# Adjusted to own needs and github'ed by Dawid Lorenz / dawid@lorenz.co
#
# To make this script run each time laptop's power adapter is plugged in/out:
# sudo cp powersave /etc/pm/power.d/
# sudo chmod +x /etc/pm/power.d/powersave
# 
# To run script manually:
# ./powersave true|false
# 
# Tested on Fedora 15, please review script and run it manually before putting
# under /etc/pm/power.d/
# ===========================================================================

# List of modules to unload, space seperated. Edit depending on your hardware and preferences.
modlist=""

# Bus list for runtime pm. Probably shouldn't touch this.
#buslist="pci spi i2c"
buslist="pci i2c" # spi didn't work in Fedora 15 - DL

case "$1" in
    # Enable some power saving settings while on battery
    true)    
        # Enable laptop mode
        echo 5 > /proc/sys/vm/laptop_mode
        
        # Disable NMI watchdog
        echo 0 > /proc/sys/kernel/nmi_watchdog
        
        # Less VM disk activity. Suggested by powertop
        echo 1500 > /proc/sys/vm/dirty_writeback_centisecs
        
        # Intel power saving
        echo Y > /sys/module/snd_hda_intel/parameters/power_save_controller
        echo 1 > /sys/module/snd_hda_intel/parameters/power_save
        
        # Wireless adapter power saving
        iwconfig wlan0 power on
        
        # Disable Wake-on-LAN
        ethtool -s p34p1 wol d
        
        # USB powersaving
        for i in /sys/bus/usb/devices/*/power/autosuspend; do
            echo 1 > $i
        done
        
        # SATA power saving
        for i in /sys/class/scsi_host/host*/link_power_management_policy; do
            echo min_power > $i
        done
        
        # Disable hardware modules to save power
        for mod in $modlist; do
            grep $mod /proc/modules >/dev/null || continue
            modprobe -r $mod 2>/dev/null
        done
        
        # Enable runtime power management. Suggested by powertop.
        for bus in $buslist; do
            for i in /sys/bus/$bus/devices/*/power/control; do
                echo auto > $i
            done
        done
    ;;
    
    # Return settings to default on AC power
    false)    
        echo 0 > /proc/sys/vm/laptop_mode
        echo 1 > /proc/sys/kernel/nmi_watchdog
        echo 500 > /proc/sys/vm/dirty_writeback_centisecs
        echo N > /sys/module/snd_hda_intel/parameters/power_save_controller
        echo 0 > /sys/module/snd_hda_intel/parameters/power_save
        iwconfig wlan0 power off
        ethtool -s p34p1 wol g
        for i in /sys/bus/usb/devices/*/power/autosuspend; do
            echo 2 > $i
        done
        for i in /sys/class/scsi_host/host*/link_power_management_policy
            do echo max_performance > $i
        done
        for mod in $modlist; do
            if ! lsmod | grep $mod; then
                modprobe $mod 2>/dev/null
            fi
        done
        for bus in $buslist; do
            for i in /sys/bus/$bus/devices/*/power/control; do
                echo on > $i
            done
        done
    ;;
esac

exit 0
